name: Deploy Bakulan WEB

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'release/*'
      - 'hotfix/*'
      - 'development'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code - ${{ github.ref_name }}
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm ci
        npm build
        
  deploy:
    needs: build
    name: deploy branch - ${{ github.ref_name }}
    runs-on: ubuntu-latest

    env:
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}

    steps:
    - name: Checkout code - ${{ github.ref_name }}
      uses: actions/checkout@v2

    - name: Set up SSH - ${{ github.ref_name }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PASSWORD" > ~/.ssh/workflow_eventopia_api_password
        chmod 600 ~/.ssh/workflow_eventopia_api_password
        ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy to VPS - ${{ github.ref_name }}
      run: |
        # Connect to the server and run Docker commands
        sshpass -p "$(cat ~/.ssh/workflow_eventopia_api_password)" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "cd ~/bakulan/docker/ && ./github-workflow-fe.sh ${{ github.ref_name }} && docker-compose up -d"